//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tienda2
    {
        public int ID { get; set; }
        public string Nombre_Cliente { get; set; }
        public int Cedula_Cliente { get; set; }
        public string Tipo_Producto { get; set; }
        public string Estado_Producto { get; set; }
        public string Producto { get; set; }
        public string Sitio { get; set; }
        public string IVA { get; set; }
    }
}
